version: '3.8'

services:

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - "27017:27017"

  reactive-timesheet-app:
    image: reactive-timesheet-app
    build:
      context: k8s/local
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - "8080:8080"