# Default Setting
server:
  port: 8080

#logging:
#  level:
#    org.springframework.web : debug
#    sql: error
#    jdbc: off
#    jdbc.sqlonly: debug

# NoSQL DB Setting
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: mongodb_tutorial
      username: root
      password: root