# Default Setting
server:
  port: 8080
  error:
    include-exception: false      # Response 에 Exception 을 표시할지
    include-message: always       # Response 에 Exception Message 를 표시할지 (never | always | on_param)
    include-stacktrace: on_param  # Response 에 Stack Trace 를 표시할지 (never | always | on_param) on_trace_params 은 deprecated
    whitelabel.enabled: true      # 에러 발생 시 Spring 기본 에러 페이지 노출 여부

#logging:
#  level:
#    org.springframework.web : debug
#    sql: error
#    jdbc: off
#    jdbc.sqlonly: debug

# NoSQL DB Setting
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: mongodb_tutorial
      username: root
      password: root

#logging:
#  level:
#    io:
#      reflectoring: DEBUG
#    org:
#      springframework:
#        web: INFO
#        data:
#          mongodb:
#            core:
#              ReactiveMongoTemplate: DEBUG
#    reactor:
#      netty:
#        http:
#          client: DEBUG

# Security
springbootjjwt:
  password:
    secret: mysecret
    iteration: 33
    keylength: 256
  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
    expiration: 28800
